packaging_format = 2

id = "getsimple"
name = "GetSimple"
description.en = "Flatfile CMS that works fast and efficient"
description.fr = "Flatfile CMS that works fast and efficient"

version = "3.3.16~ynh4"

maintainers = []

[upstream]
license = "GPL-3.0"
website = "http://get-simple.info"
admindoc = "http://get-simple.info/wiki/fr:start"
code = "https://github.com/GetSimpleCMS/GetSimpleCMS"

[integration]
yunohost = ">= 11.2.18"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/getsimple"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "string"
    choices = ["de_DE", "en_US", "fr_FR", "nl_NL"]
    default = "fr_FR"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
        [resources.sources.main]
        url = "https://github.com/GetSimpleCMS/GetSimpleCMS/archive/refs/tags/v3.3.16.tar.gz"
        sha256 = "2c012c0346ba8088f7ccec809653b177a43de6d87c6f1c826d26df3956a84fb0"
        autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.2-xml php8.2-curl php8.2-gd php8.2-zip php8.2-xml"
