#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

timezone="$(cat /etc/timezone)"
email=$(ynh_user_get_info --username=$admin --key="mail")

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=5

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring PHP-FPM..." --weight=1

ynh_add_fpm_config

ynh_add_nginx_config

#=================================================
# SPECIFIC SETUP
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

ynh_add_config --template="temp.gsconfig.php" --destination="$install_dir/gsconfig.php"

chmod 400 "$install_dir/gsconfig.php"
chown $app:$app "$install_dir/gsconfig.php"

#=================================================
# SETUP APPLICATION WITH CURL
#=================================================
ynh_script_progression --message="Setuping application with CURL..."

# Installation with curl
ynh_script_progression --message="Finalizing installation..."
ynh_local_curl "/admin/install.php" "lang=$language" "continue=continue"
ynh_local_curl "/admin/setup.php" "siteurl=https://$domain$path" "lang=$language" "sitename=YunoHost" "user=$admin" "email=$email" "submitted=submitted"
ynh_local_curl "/admin/support.php" "updated=2"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
